config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "dashboard#index", :as => "authenticated_root"
  end
  
  root 'welcome#index'
  
  # Devise routes we skip the registration routes and them recreate them manually
  # leaving out edit and update as those are implemented in the users controller
  devise_for :users, controllers: {registrations: 'users'}
  
  
  # Route for user to generate a reset password email
  # For security I have disallowed users from changing their password
  # directly on the profile page. They must click this link which will send them
  # an email with a password reset token. This is to increase security so that if
  # a user left their session up no one can just go to account page and change their 
  # password, they must also have access to the users email address.
  devise_scope :user do
    post 'users/password/reset', to: 'users#password_reset', as: :reset_user_password
  end
  
  resources :users, only: [] do
    resources :items, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  validates :first_name, presence: true
  validates :last_name,  presence: true
  
  belongs_to :time_zone
  has_many :items, dependent: :destroy
  
  scope :users_for_summary_email_at_6, -> {
    joins(:time_zone).
    where(allow_email_reminders: true).
    where(time_zones: {name: TimeZone.current_local_zone_hour_is(6)})
  }
  
  def full_name
    (first_name + ' ' + last_name).titleize
  end
  
  def configured_time_zone
    if time_zone
      time_zone.name
    else
      'Etc/UTC'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :authenticate_user!
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    
    @user.assign_attributes(user_params)
    
    # check if email was updated
    if @user.email_changed?
      extra_info = " A confirmation email was sent to \"" + params[:user][:email] + "\". Please follow the email instructions to confirm your new email."
    else
      extra_info = ''
    end
    
    if @user.save
      flash[:notice] = "Account settings updated successfully.#{extra_info}"
      redirect_to edit_user_registration_path
    else
      flash.now[:error] = "There was a problem updating your account"
      render :edit
    end
  end
  
  def password_reset
    current_user.send_reset_password_instructions
    
    if !successfully_sent?(current_user)
      flash[:error] = "There was a prolem sending your reset password email. Please try again."
    end
      
    redirect_to edit_user_registration_path
  end
    
  private
  
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :time_zone_id, :allow_email_reminders, :email_reminders_days)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def options_for_timezone
    TimeZone.all.map do |zone|
      [zone.description, zone.id]
    end
  end
  
  def options_for_email_reminder_days
    [[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7]]
  end
end

app/views/users/edit.html.haml
= render 'shared/header'
.container
  %h1#page-title Account Settings

  .panel.panel-default
    .panel-heading
      %h2.panel-title Profile Settings
    .panel-body
      = form_for @user, url: user_registration_path, html: { class: 'form-horizontal' } do |f|
        #form-messages
          = display_form_errors!(@user)

        = form_group_tag(@user.errors[:first_name], false) do
          = f.label :first_name, class: 'col-sm-3 control-label'
          .col-sm-5
            = f.text_field :first_name, class: 'form-control'

        = form_group_tag(@user.errors[:last_name], false) do
          = f.label :last_name, class: 'col-sm-3 control-label'
          .col-sm-5
            = f.text_field :last_name, class: 'form-control'

        = form_group_tag(@user.errors[:email], false) do
          = f.label :email, class: 'col-sm-3 control-label'
          .col-sm-5
            = f.email_field :email, class: 'form-control'

        .form-group
          = f.label :time_zone_id, class: 'col-sm-3 control-label'
          .col-sm-5
            = f.select :time_zone_id, options_for_timezone, {}, class: 'form-control'
        
        .form-group
          %label.col-sm-3.control-label{for: 'password-reset-button'} Reset Password
          .col-sm-5
            = link_to "Send Password Reset Email",reset_user_password_path, method: :post, id: 'password-reset-button', class: 'btn btn-info'

        .form-group
          .col-sm-offset-3.col-sm-5
            = f.submit "Update Profile", class: 'btn btn-success'
  
  .panel.panel-default
    .panel-heading
      %h2.panel-title Email Settings
    .panel-body
      = form_for @user, url: user_registration_path, html: { class: 'form-horizontal' } do |f|
        .form-group
          %label#email-settings-label.col-sm-3.control-label{for: 'user_allow_email_reminders'} Task Reminder Settings
          .col-sm-5#email-settings-section
            = f.label :allow_email_reminders do
              = f.check_box :allow_email_reminders, id: 'allow-email-checkbox'
              Allow email reminders for tasks to be sent
            <br>

            Email reminders will be sent #{f.select :email_reminders_days, options_for_email_reminder_days, {}, id: 'email-days-select', class: 'form-control'} days before tasks expire
        
        .form-group
          .col-sm-offset-3.col-sm-5
            = f.submit "Update Email Settings", class: 'btn btn-success'

  .panel.panel-default
    .panel-heading
      %h2.panel-title Cancel Account
    .panel-body
      .row
        %label.col-sm-3.control-label.text-right#cancel-account-label{for: 'cancel-account-link'} Cancel Your Account
        .col-sm-5
          = link_to "Click Here to Cancel", user_registration_path, data: { confirm: "Are you sure?" }, method: :delete, id: 'cancel-account-link', class: 'btn btn-danger'